### ISSUE TITLE
mxj midifile does not load

### ISSUE THREAD

**Issue by ramagottfried** [CNMAT/CNMAT-Externs#35]
java.lang.UnsatisfiedLinkError: com.cycling74.max.MaxSystem.getDefaultPath()Ljava/lang/String;
    at com.cycling74.max.MaxSystem.getDefaultPath(Native Method)
    at com.cycling74.max.MXJClassLoaderImpl.lookupClassData(MXJClassLoaderImpl.java:164)
    at com.cycling74.max.MXJClassLoaderImpl.doLoadClass(MXJClassLoaderImpl.java:111)
    at com.cycling74.max.MXJClassLoader.loadClazz(MXJClassLoader.java:88)
Could not load class 'midifile'

**Comment by adrianfreed** [comment]
which help patches needs this?

**Comment by ramagottfried** [comment]
as far as I know only the midifile help patch in the Externals/help uses it.

**Comment by equilet** [comment]
If we end up distributing midifile (which we should), we need to include instructions for installing it, and make sure that we include a `/java` dir in the externals release.

**Comment by equilet** [comment]
https://github.com/CNMAT/CNMAT-Externs/issues/20
